### ISSUE TITLE
Usage instructions are unclear

### ISSUE THREAD

**Issue by mrchucho** [redis/hiredis-rb#47]
To use hiredis-rb with redis-rb, do I need to specify the driver when creating a connection?

```ruby
Redis.new(url:'redis://localhost:6379/0', driver: :hiredis)
```

Or is it sufficient to follow the [instructions](https://github.com/redis/hiredis-rb#redis-rb) and just do the following?

```
gem "hiredis", "~> 0.6.0"
gem "redis", ">= 3.2.0", :require => ["redis", "redis/connection/hiredis"]
```
and
```ruby
Redis.new(url: 'redis://localhost:6379/0')
```

Or do I need to do both?

**Comment by badboy** [comment]
If nothing else is specified, the last loaded driver will be used. So if you explicitely load `redis/connection/hiredis`, hiredis will be used.
IMO you should just make it explicit in the code and use `:driver => :hiredis`, so everyone sees it right away when reading the code, instead of relying on Gemfile magic.

**Comment by mrchucho** [comment]
Thanks for the quick response!
